### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/landing-page#22]
- Interactive Business Card
- Optimize Rendering (remove PBR, maybe make GIF)
- Logo?
- DAOcreator -> Tools (dropdown) -> Cotary Create
- Color scheme is dark

**Comment by orishim** [comment]
I’d also be curious to see the previous cases which had different colors, and then a blank background (maybe black)

**Comment by nickplace** [comment]
> * Interactive Business Card
> * Optimize Rendering (remove PBR, maybe make GIF)
> * Logo?
> * DAOcreator -> Tools (dropdown) -> Cotary Create
> * Color scheme is dark

Do you have that cool modular background without the logo on top?

**Comment by orishim** [comment]
Unfortunately not, DAOstack made it for us way back. I'll send you some similar ones I have
