### ISSUE TITLE
Add "Press" section

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page#33]
With coindesk, cointelegraph, MIT icons that link to articles

Not sure where is best to fit this in.

**Comment by nickplace** [comment]
Maybe this goes under "More"?

**Comment by nickplace** [comment]
![image](https://user-images.githubusercontent.com/707129/76345548-2c55f200-62c9-11ea-8866-6dfd1edc23b7.png)

@orishim How do you feel about putting these in another dropdown?

**Comment by orishim** [comment]
Another option is doing something like this:

![Group](https://user-images.githubusercontent.com/10736693/76365002-a6539e80-62fc-11ea-95b4-ac84fbc46f7b.png)

**Comment by orishim** [comment]
https://github.com/dOrgTech/landing-page/pull/44
