### ISSUE TITLE
Show Case Labels / Categories

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/landing-page#39]
For each "case", have labels / tags / categories for what was done. Here are some examples:
- Wep App
- Mobile App
- Design
- Smart Contracts
- Security Audit
- Developer Tooling
- Technical Specification

etc...

**Comment by nickplace** [comment]
@dOrgJelli Totally!

Information request: https://docs.zoho.com/file/7um7a857239c8f23044a5805f4e1164aae438

**Comment by orishim** [comment]
https://github.com/dOrgTech/landing-page/pull/53
