### ISSUE TITLE
Add metrics section to homepage

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page#59]
Add section with metrics about dOrg's impact
- Value exchanged through dapps we've built (OpenRaise, Balancer, Nec Boostrapper)
- Projects completed (Airtable API)
- DAOs launched? (DAOcreator)

**Comment by Phinneas** [comment]
Where do you find the metrics to fill this out? Where are they stored?

**Comment by rihp** [comment]
We could look into sites like https://www.duneanalytics.com/

**Comment by orishim** [comment]
Included in the redesign at https://github.com/dOrgTech/Ops/issues/37
